// Copy the canonical engine (../src) into web/lib/engine so the web app is
// self-contained and deploys without reaching outside its own directory.
// Source of truth stays ../src; this runs on predev/prebuild. DO NOT edit the
// generated copies — edit ../src and re-run.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const FILES = ["types.ts", "fingerprints.ts", "detect.ts", "fetch.ts"];
const banner = "// AUTOGENERATED from ../../src by scripts/sync-engine.mjs - DO NOT EDIT.\n";

const outDir = new URL("../lib/engine/", import.meta.url);
mkdirSync(outDir, { recursive: true });

// On a standalone deploy (web/ only, no ../src) the committed copy is used as-is.
const srcRoot = new URL("../../src/", import.meta.url);
if (!existsSync(srcRoot)) {
  console.log("sync-engine: ../src not present, using committed lib/engine copy.");
  process.exit(0);
}

for (const f of FILES) {
  const src = readFileSync(new URL(`../../src/${f}`, import.meta.url), "utf8");
  writeFileSync(new URL(`../lib/engine/${f}`, import.meta.url), banner + src);
  console.log(`synced lib/engine/${f}`);
}
