// AUTOGENERATED from ../../src by scripts/sync-engine.mjs - DO NOT EDIT.
import { FINGERPRINTS } from "./fingerprints.js";
import type { Category, Detection, Evidence, PageInput, Signal } from "./types.js";

// Try to match one signal against the page. Returns the matched text (receipt)
// or null. Pure and deterministic — same input always yields the same output.
function matchSignal(sig: Signal, page: PageInput): string | null {
  const html = page.html ?? "";
  const headers = page.headers ?? {};

  if (sig.type === "header") {
    const idx = sig.pattern.indexOf(":");
    const name = (idx === -1 ? sig.pattern : sig.pattern.slice(0, idx)).toLowerCase();
    const valuePattern = idx === -1 ? "" : sig.pattern.slice(idx + 1);
    const value = headers[name];
    if (value == null) return null;
    if (!valuePattern) return `${name}: ${value}`;
    return new RegExp(valuePattern, "i").test(value) ? `${name}: ${value}` : null;
  }

  if (sig.type === "url") {
    const u = page.url ?? "";
    return new RegExp(sig.pattern, "i").test(u) ? u : null;
  }

  if (sig.type === "metaGenerator") {
    const re = new RegExp(
      `<meta[^>]+name=["']generator["'][^>]+content=["']([^"']*${sig.pattern}[^"']*)["']`,
      "i",
    );
    const m = html.match(re);
    return m ? m[1] : null;
  }

  // The rest must match a REAL resource/attribute, not a string in prose or a
  // quoted code sample. This is the main defense against false positives (a
  // tutorial mentioning gptengineer.js must not register as Lovable).
  for (const re of effectiveRegexes(sig)) {
    const m = html.match(re);
    if (m) return truncate(m[1] ?? m[0]);
  }
  return null;
}

// Build the regex(es) that bind a signal to an actual resource position.
function effectiveRegexes(sig: Signal): RegExp[] {
  const p = sig.pattern;
  switch (sig.type) {
    case "script":
      // only inside <script ... src="...PATTERN...">
      return [new RegExp(`<script\\b[^>]*\\bsrc\\s*=\\s*["'][^"']*(${p})`, "i")];
    case "asset":
      // inside an attribute URL (src/href/srcset/poster) or a CSS url()
      return [
        new RegExp(`(?:src|href|srcset|poster|content)\\s*=\\s*["'][^"']*(${p})`, "i"),
        new RegExp(`url\\(\\s*["']?[^"')]*(${p})`, "i"),
      ];
    case "attr":
      // must sit at an attribute boundary, not mid-word in text
      return [new RegExp(`(?:^|[\\s"'<])(${p})`, "i")];
    case "html":
    default:
      // structural markers a builder injects (comments, data blobs) — loose by design
      return [new RegExp(`(${p})`, "i")];
  }
}

function truncate(s: string, n = 140): string {
  const clean = s.replace(/\s+/g, " ").trim();
  return clean.length > n ? clean.slice(0, n) + "…" : clean;
}

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

// Run every fingerprint against the page and return scored detections, highest first.
export function detect(page: PageInput): Detection[] {
  const out: Detection[] = [];
  for (const fp of FINGERPRINTS) {
    const evidence: Evidence[] = [];
    let score = 0;
    let definitive = false;
    for (const sig of fp.signals) {
      const matched = matchSignal(sig, page);
      if (matched !== null) {
        score += sig.weight;
        const isDef = sig.definitive === true;
        definitive ||= isDef;
        evidence.push({ note: sig.note, weight: sig.weight, matched, definitive: isDef });
      }
    }
    if (score > 0) {
      out.push({
        id: fp.id,
        name: fp.name,
        category: fp.category,
        score: round(score),
        confidence: Math.min(1, round(score)),
        definitive,
        evidence: evidence.sort((a, b) => b.weight - a.weight),
      });
    }
  }
  return out.sort((a, b) => b.score - a.score);
}

const MAKER_CATEGORIES: Category[] = ["ai-coding-agent", "ai-site-builder", "no-code", "cms"];

// A maker needs real evidence, not one stray asset path, before we name it.
// Anything weaker is noise (e.g. a blog link exposing /wp-json on a Framer site).
const MAKER_CONFIDENCE_FLOOR = 0.5;

export type VerdictKind = "named" | "inferred" | "clean" | "unknown";

export interface Verdict {
  kind: VerdictKind;
  headline: string; // the one-line answer, shared by CLI / extension / web
  detail: string; // the honest explanation under it
  maker: Detection | null; // best guess at who built it
  inferredAgent: string | null; // heuristic when no explicit maker marker exists
  makers: Detection[];
  weakMakerSignals: Detection[]; // matched, but below the naming threshold
  stack: Detection[]; // framework-level context
  hosts: Detection[];
  all: Detection[];
}

// Turn raw detections into a single human-facing verdict.
export function verdict(page: PageInput): Verdict {
  const all = detect(page);
  const makerHits = all.filter((d) => MAKER_CATEGORIES.includes(d.category));
  // To NAME a maker we require BOTH a definitive marker and enough confidence.
  // Everything else is downgraded to "weak signals" and never put on the verdict.
  const makers = makerHits.filter((d) => d.definitive && d.confidence >= MAKER_CONFIDENCE_FLOOR);
  const weakMakerSignals = makerHits.filter((d) => !(d.definitive && d.confidence >= MAKER_CONFIDENCE_FLOOR));
  const stack = all.filter((d) => d.category === "framework");
  const hosts = all.filter((d) => d.category === "host");

  // Heuristic: a Next + shadcn (+ Geist) (+ Vercel) cluster with no explicit
  // maker marker is the signature of the v0/Lovable/Bolt family.
  const has = (id: string) => all.some((d) => d.id === id);
  let inferredAgent: string | null = null;
  if (makers.length === 0 && has("shadcn") && (has("nextjs") || has("vite-react"))) {
    if (has("geist") || has("vercel")) {
      inferredAgent = "likely an AI coding agent (Next + shadcn + Geist/Vercel cluster — v0 / Lovable / Bolt family)";
    } else {
      inferredAgent = "possibly an AI coding agent (shadcn + React stack, no explicit marker)";
    }
  }

  const maker = makers[0] ?? null;

  // One honest message, computed once, reused everywhere. "No fingerprint" is a
  // correct answer (hand-coded / AI-assistant-built), not a failure — say so.
  let kind: VerdictKind;
  let headline: string;
  let detail: string;
  if (maker) {
    kind = "named";
    headline = `Built with ${maker.name}`;
    detail = `${pct(maker.confidence)} confidence · backed by a definitive marker`;
  } else if (inferredAgent) {
    kind = "inferred";
    headline = "Best guess: AI coding agent";
    detail = "Stack matches the v0 / Lovable / Bolt family, but there's no definitive marker. Stacks suggest, they don't prove.";
  } else if (stack.length > 0) {
    kind = "clean";
    headline = "No builder fingerprint";
    detail = "Hand-coded, or built with an AI coding assistant (Claude, Cursor, Copilot). These write plain code and leave no fingerprint by design. This is a correct result, not a miss.";
  } else {
    kind = "unknown";
    headline = "No fingerprint found";
    detail = "Likely hand-built, or made with a builder we don't fingerprint yet.";
  }

  return { kind, headline, detail, maker, inferredAgent, makers, weakMakerSignals, stack, hosts, all };
}

function pct(n: number): string {
  return `${Math.round(n * 100)}%`;
}
