// AUTOGENERATED from ../../src by scripts/sync-engine.mjs - DO NOT EDIT.
import type { Fingerprint } from "./types.js";

// The signature database. Each entry is a maker (or stack component) plus the
// observable signals that betray it. Weights: ~0.9 = definitive on its own,
// ~0.4-0.6 = strong, ~0.2-0.3 = supporting (only meaningful in combination).
//
// Ground truth note: every signal here is harvestable. To verify or extend,
// generate a site with the builder and inspect the shipped HTML/headers.
export const FINGERPRINTS: Fingerprint[] = [
  // ---------------------------------------------------------------- AI coding agents
  {
    id: "lovable",
    name: "Lovable",
    category: "ai-coding-agent",
    url: "https://lovable.dev",
    signals: [
      { type: "script", pattern: "cdn\\.gpteng\\.co/gptengineer\\.js", weight: 0.95, note: "Loads gptengineer.js (Lovable / GPT Engineer runtime)", definitive: true },
      { type: "url", pattern: "\\.lovableproject\\.com", weight: 0.8, note: "Served from lovableproject.com", definitive: true },
      { type: "url", pattern: "\\.lovable\\.(app|dev)", weight: 0.7, note: "Served from Lovable hosting", definitive: true },
      { type: "metaGenerator", pattern: "Lovable", weight: 0.9, note: "generator meta tag = Lovable", definitive: true },
    ],
  },
  {
    id: "v0",
    name: "v0 (Vercel)",
    category: "ai-coding-agent",
    url: "https://v0.dev",
    signals: [
      { type: "html", pattern: "Generated by v0", weight: 0.95, note: "'Generated by v0' marker in HTML", definitive: true },
      { type: "url", pattern: "v0-[a-z0-9-]+\\.vercel\\.app", weight: 0.8, note: "Served from a v0 preview URL", definitive: true },
    ],
  },
  {
    id: "bolt",
    name: "Bolt (StackBlitz)",
    category: "ai-coding-agent",
    url: "https://bolt.new",
    signals: [
      { type: "html", pattern: "Generated by Bolt", weight: 0.9, note: "'Generated by Bolt' marker", definitive: true },
      { type: "asset", pattern: "bolt\\.new", weight: 0.4, note: "References bolt.new (link, not proof)" },
      { type: "asset", pattern: "stackblitz", weight: 0.4, note: "StackBlitz asset (Bolt's host)" },
    ],
  },

  // ---------------------------------------------------------------- AI / no-code site builders
  {
    id: "framer",
    name: "Framer",
    category: "no-code",
    url: "https://framer.com",
    signals: [
      { type: "metaGenerator", pattern: "Framer", weight: 0.9, note: "generator meta tag = Framer", definitive: true },
      { type: "asset", pattern: "framerusercontent\\.com", weight: 0.7, note: "Assets from framerusercontent.com", definitive: true },
      { type: "script", pattern: "events\\.framer\\.com", weight: 0.5, note: "Framer analytics script" },
      { type: "html", pattern: "class=\"framer-", weight: 0.3, note: "framer- prefixed classes" },
    ],
  },
  {
    id: "webflow",
    name: "Webflow",
    category: "no-code",
    url: "https://webflow.com",
    signals: [
      { type: "metaGenerator", pattern: "Webflow", weight: 0.9, note: "generator meta tag = Webflow", definitive: true },
      { type: "attr", pattern: "data-wf-(page|site)", weight: 0.7, note: "data-wf-page / data-wf-site attribute", definitive: true },
      { type: "asset", pattern: "(assets\\.website-files\\.com|website-files\\.com)", weight: 0.5, note: "Webflow asset CDN" },
      { type: "html", pattern: "class=\"[^\"]*\\bw-(nav|container|button|row)\\b", weight: 0.3, note: "w- prefixed Webflow classes" },
    ],
  },
  {
    id: "wix",
    name: "Wix",
    category: "no-code",
    url: "https://wix.com",
    signals: [
      { type: "metaGenerator", pattern: "Wix\\.com", weight: 0.9, note: "generator meta tag = Wix.com Website Builder", definitive: true },
      { type: "header", pattern: "x-wix-request-id:", weight: 0.7, note: "X-Wix-Request-Id response header", definitive: true },
      { type: "asset", pattern: "static\\.wixstatic\\.com", weight: 0.6, note: "wixstatic.com asset CDN" },
      { type: "html", pattern: "wix-warmup-data", weight: 0.5, note: "wix-warmup-data payload" },
    ],
  },
  {
    id: "squarespace",
    name: "Squarespace",
    category: "no-code",
    url: "https://squarespace.com",
    signals: [
      { type: "html", pattern: "This is Squarespace", weight: 0.9, note: "'This is Squarespace' HTML comment", definitive: true },
      { type: "metaGenerator", pattern: "Squarespace", weight: 0.9, note: "generator meta tag = Squarespace", definitive: true },
      { type: "asset", pattern: "(static1\\.squarespace\\.com|squarespace-cdn\\.com)", weight: 0.5, note: "Squarespace CDN" },
    ],
  },
  {
    id: "durable",
    name: "Durable",
    category: "ai-site-builder",
    url: "https://durable.co",
    signals: [
      { type: "url", pattern: "\\.durable\\.co", weight: 0.8, note: "Served from durable.co", definitive: true },
      { type: "attr", pattern: "data-durable", weight: 0.6, note: "data-durable attribute", definitive: true },
    ],
  },
  {
    id: "carrd",
    name: "Carrd",
    category: "no-code",
    url: "https://carrd.co",
    signals: [
      { type: "url", pattern: "\\.carrd\\.co", weight: 0.8, note: "Served from carrd.co", definitive: true },
      { type: "attr", pattern: "id=\"carrd\"", weight: 0.6, note: "#carrd root element", definitive: true },
    ],
  },

  // ---------------------------------------------------------------- CMS
  {
    id: "wordpress",
    name: "WordPress",
    category: "cms",
    url: "https://wordpress.org",
    signals: [
      { type: "metaGenerator", pattern: "WordPress", weight: 0.85, note: "generator meta tag = WordPress", definitive: true },
      { type: "asset", pattern: "/wp-content/", weight: 0.5, note: "/wp-content/ asset paths" },
      { type: "asset", pattern: "/wp-(includes|json)/", weight: 0.4, note: "wp-includes / wp-json paths" },
    ],
  },

  // ---------------------------------------------------------------- Stack / framework context
  // These are not "makers" but the combination (Next + shadcn + Geist + Vercel)
  // is a strong tell for the AI-coding-agent family.
  {
    id: "nextjs",
    name: "Next.js",
    category: "framework",
    url: "https://nextjs.org",
    signals: [
      { type: "html", pattern: "/_next/static/", weight: 0.6, note: "/_next/static/ bundle paths" },
      { type: "attr", pattern: "id=\"__next\"", weight: 0.5, note: "#__next root element" },
      { type: "script", pattern: "/_next/static/chunks/", weight: 0.4, note: "Next.js chunk scripts" },
    ],
  },
  {
    id: "vite-react",
    name: "Vite + React",
    category: "framework",
    url: "https://vitejs.dev",
    signals: [
      { type: "script", pattern: "/assets/index-[A-Za-z0-9_]+\\.js", weight: 0.4, note: "Vite hashed entry bundle" },
      { type: "script", pattern: "@vite/client", weight: 0.5, note: "Vite dev client" },
      { type: "attr", pattern: "id=\"root\"", weight: 0.2, note: "#root mount (React/Vite default)" },
    ],
  },
  {
    id: "shadcn",
    name: "shadcn/ui",
    category: "framework",
    url: "https://ui.shadcn.com",
    signals: [
      { type: "html", pattern: "data-\\[state=", weight: 0.3, note: "data-[state=] Radix/shadcn class hooks" },
      { type: "html", pattern: "(bg-background|text-foreground|text-muted-foreground)", weight: 0.3, note: "shadcn semantic Tailwind tokens" },
      { type: "asset", pattern: "lucide", weight: 0.2, note: "lucide-react icons (shadcn default)" },
    ],
  },
  {
    id: "geist",
    name: "Geist font",
    category: "framework",
    url: "https://vercel.com/font",
    signals: [
      { type: "html", pattern: "(__geist|Geist|geist-sans)", weight: 0.3, note: "Geist font (Vercel / v0 default)" },
    ],
  },

  // ---------------------------------------------------------------- Hosts
  {
    id: "vercel",
    name: "Vercel",
    category: "host",
    url: "https://vercel.com",
    signals: [
      { type: "header", pattern: "server:Vercel", weight: 0.4, note: "Server: Vercel header" },
      { type: "header", pattern: "x-vercel-id:", weight: 0.6, note: "x-vercel-id header" },
    ],
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "host",
    url: "https://netlify.com",
    signals: [
      { type: "header", pattern: "server:Netlify", weight: 0.6, note: "Server: Netlify header" },
      { type: "header", pattern: "x-nf-request-id:", weight: 0.5, note: "x-nf-request-id header" },
    ],
  },
  {
    id: "replit",
    name: "Replit",
    category: "host",
    url: "https://replit.com",
    signals: [
      { type: "url", pattern: "\\.(replit\\.app|replit\\.dev|repl\\.co)", weight: 0.6, note: "Served from Replit hosting" },
    ],
  },
];
