// AUTOGENERATED from ../../src by scripts/sync-engine.mjs - DO NOT EDIT.
// Core types for the provenance detection engine.

// How a single signal is matched against a page.
//  - header        : "name:valueRegex" (valueRegex optional => presence only)
//  - metaGenerator : substring/regex expected inside <meta name="generator" content="...">
//  - html          : regex run over the raw HTML
//  - script        : regex expected in a <script src="..."> (run over raw HTML)
//  - asset         : regex for a host/domain expected anywhere in the HTML
//  - attr          : regex for an attribute expected in the HTML
export type SignalType =
  | "header"
  | "metaGenerator"
  | "html"
  | "script"
  | "asset"
  | "attr"
  | "url"; // matches the page's own address (served-from), not a link in the body

export interface Signal {
  type: SignalType;
  pattern: string; // regex source (case-insensitive). For "header" use "name:valueRegex".
  weight: number; // contribution to the builder's score (definitive ~0.9, supporting ~0.2-0.4)
  note: string; // human-readable evidence description
  definitive?: boolean; // a marker only this builder ships — required to NAME a maker
}

export type Category =
  | "ai-coding-agent" // v0, Lovable, Bolt — LLM that writes real code
  | "ai-site-builder" // Durable, Wix ADI — AI no-code
  | "no-code" // Framer, Webflow, Wix, Squarespace, Carrd
  | "cms" // WordPress
  | "framework" // Next.js, Vite, shadcn, etc. (stack context, not a "maker")
  | "host"; // Vercel, Netlify, Replit

export interface Fingerprint {
  id: string;
  name: string;
  category: Category;
  url?: string;
  signals: Signal[];
}

export interface Evidence {
  note: string;
  weight: number;
  matched: string; // the actual text that matched, for receipts
  definitive: boolean;
}

export interface Detection {
  id: string;
  name: string;
  category: Category;
  score: number;
  confidence: number; // 0..1
  definitive: boolean; // at least one definitive signal matched
  evidence: Evidence[];
}

export interface PageInput {
  url?: string;
  html: string;
  headers?: Record<string, string>; // keys should be lowercased
}
